### ISSUE TITLE
ENOTFOUND Package angular-spinner not found

### ISSUE THREAD

**Issue by fsebbah** [urish/angular-spinner#100]
It seems the package is not published on the bower repo.
bower                        ENOTFOUND Package angular-spinner not found

**Comment by Attrash-Islam** [comment]
Absolutely @fsebbah  , I'll take care of that ASAP.
Thanks for reporting!

**Comment by fsebbah** [comment]
Ouf, i believe I was crazy

**Comment by Attrash-Islam** [comment]
Sorry, but we were upgrading the whole codebase. I'll resolve that

**Comment by Attrash-Islam** [comment]
Fixed. bower install as you like (v.1.0.1)

**Comment by fsebbah** [comment]
Cool, it works.

**Comment by Attrash-Islam** [comment]
Thanks :smiley:
