### ISSUE TITLE
Bower package does not contain dist directory

### ISSUE THREAD

**Issue by Guiswa** [urish/angular-spinner#101]
Bower package does not contain dist directory. If this is intentional, the readme is now incorrect as it does not specify a build step.

Also, attempting to build the project on my system via `npm run build` results in:

`Tell the author that this fails on your system:`
`npm ERR!     rimraf ./dist`

OS X 10.12.3
Node 7.4.0
NPM 4.1.1

**Comment by Attrash-Islam** [comment]
Hi @Guiswa ,

Bower is working and having dist folder.
See this:

<img src="https://cdn.rawgit.com/Attrash-Islam/assets/d3944c62/anim.gif" />

Before `npm run build` you must run `npm i` to install rimraf package and all other package

Hope that will help :wink:

**Comment by Guiswa** [comment]
See below for what I get after running `bower install angular-spinner@1.0.1`:

![screen shot 2017-01-25 at 1 01 52 pm](https://cloud.githubusercontent.com/assets/464703/22309095/9ddca62e-e2fe-11e6-865f-bf98ce91da51.png)

**Comment by Attrash-Islam** [comment]
Can you please run `bower cache clean` and then install it again?

**Comment by Guiswa** [comment]
Aha, that was the trick. Weird, since I've never had a problem with Bower cache before. In any case, I'm happy to be an example in case anyone else is seeing this issue.

**Comment by Attrash-Islam** [comment]
Sometimes, Bower caches the packages in a wrong way. I'm glad I helped :smiley:
