### ISSUE TITLE
TypeError: SpinnerConstructor is not a constructor

### ISSUE THREAD

**Issue by nikhiltech** [urish/angular-spinner#102]
I am using spinner as mentioned on plunker example but it is giving typeerror as 'SpinnerConstructor is not a constructor'. I am using chrome.
fULL eRROR: TypeError: SpinnerConstructor is not a constructor
    at angular-spinner.js:57
    at m.$digest (angular.js:17800)
    at m.$apply (angular.js:18066)
    at HTMLElement.<anonymous> (angular.js:26678)
    at HTMLElement.dispatch (jquery-1.10.2.min.js:22)
    at HTMLElement.v.handle (jquery-1.10.2.min.js:22)

**Comment by Attrash-Islam** [comment]
Hi and thanks for reporting..
Can you please generate plunker that shows the problems? How do you use this library? And what options you're passing to ui-spinner directive?

Thanks

**Comment by Attrash-Islam** [comment]
Any new progress regards this issue @nikhiltech ?

**Comment by nikhiltech** [comment]
Issue got fixed when I included spin.js file.

**Comment by Attrash-Islam** [comment]
Weird. Because spin.js is included into the bundle? Which version of the plugin you're using?

**Comment by nikhiltech** [comment]
I didn't check version but I only downloaded only angular-spinner.js, After the issue i added spin.js

**Comment by Attrash-Islam** [comment]
Thanks. Can you please tell me how you downloaded angular-spinner?

**Comment by ladjzero** [comment]
Same issue. I got angular-spinner via CDN <script src="//cdn.bootcss.com/angular-spinner/0.8.1/angular-spinner.min.js"></script>

**Comment by Attrash-Islam** [comment]
use the last version 1.0.1 because we've some breaking changes, before this version (also in 0.8.1) we were requesting from the library users to include also spin.js but now in the last stable version you're not forced to include it

**Comment by Attrash-Islam** [comment]
See README
