### ISSUE TITLE
Run angular-spinner locally (npm i error)

### ISSUE THREAD

**Issue by dtslvr** [urish/angular-spinner#104]
Hi guys,

We tried to run _angular-spinner_ locally and followed the instructions in the readme file. When we run `npm i`we get the following error:

```
npm ERR! code E404
npm ERR! 404 Not Found: api
npm ERR! 404 
npm ERR! 404  'api' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-spinner'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

```
npm -v
4.4.1
```

Thanks for your support,
Thomas

**Comment by Attrash-Islam** [comment]
Hi @dtslvr ,
Thanks for reporting..

It's working in my side, see the attached GIF.
![angular-spinner-npm](https://cloud.githubusercontent.com/assets/7091543/24102645/5609e5b2-0d85-11e7-8286-2e5dbc2c9846.gif)

How do you install it?

**Comment by dtslvr** [comment]
1.  `git clone https://github.com/urish/angular-spinner.git`
2. `cd angular-spinner `
3. `npm i`
```
npm ERR! code E404
npm ERR! 404 Not Found: api
npm ERR! 404 
npm ERR! 404  'api' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-spinner'
```

**Comment by Attrash-Islam** [comment]
@dtslvr To make sure you get notified since GitHub was down for minutes

**Comment by Attrash-Islam** [comment]
@dtslvr , At me the same commands is working. Give me the chance to check more

**Comment by Attrash-Islam** [comment]
Can you please run `npm cache clean` and then your commands above?

**Comment by dtslvr** [comment]
> Can you please run npm cache clean and then your commands above?

Thanks, I've just checked and it is not helping. Any other ideas?

**Comment by Attrash-Islam** [comment]
Any thoughts @urish ?

**Comment by urish** [comment]
private repo?

see https://github.com/npm/npm-registry-client/issues/80#issuecomment-230673893

**Comment by dtslvr** [comment]
> private repo?
> see npm/npm-registry-client#80 (comment)

Wow, you're amazing. The private repo seems to have problems with `"@types/angular": "1.6.1"`, etc.
I've just added a file `.npmrc`to the project folder with the following content to reset the private repo and everything works:
`registry = https://registry.npmjs.com/`

**Comment by Attrash-Islam** [comment]
Feel free to close the issue @dtslvr . Thanks @urish

**Comment by urish** [comment]
:+1
