### ISSUE TITLE
Problem with Angular Spinner and Karma/Jasmine

### ISSUE THREAD

**Issue by dulcetti** [urish/angular-spinner#105]
Hi people.

I created a spec to my Controller inside Angular 1.6.1. In my Data Service I call the `usSpinnerService.spin('spinner-content');`, but because this line the Jasmine show me the error `Looking up elements via selectors is not supported by jqLite!`

I think is because the element inside the HTML `<div id="spinner-content" us-spinner spinner-key="spinner-content"></div>`, because in the browser everything is normal.

My version of Angular Spinner is 0.8.1.

Regards.

**Comment by Attrash-Islam** [comment]
Hi @dulcetti and Thanks for reporting..
What happens when you add jquery in the 'files' of karma configuration?

I'll check if we're using JQuery, and mostly will refactor that to native JavaScript (DOM)

**Comment by Attrash-Islam** [comment]
As I saw, we just use element[0] from the directive as jqlite usage. I'll try with angular 1.6.1 because there's a breaking changes in jqlite as mentioned in the `Migration` section

**Comment by dulcetti** [comment]
Sorry for the late response. Yeah, the breking change on the `1.6.x` of AngularJS break the tests. But now is works fine.

Regards

**Comment by ghost** [comment]
I'm glad you handle it :)
