### ISSUE TITLE
RequireJS + AngularJS + angular-spinner: 

### ISSUE THREAD

**Issue by amyhickman** [urish/angular-spinner#107]
I'm unable to configure the spinner.  

	define(["require", "exports"], function (require, exports) {
		Object.defineProperty(exports, "__esModule", { value: true });
		var SpinnerConfigurator = (function () {
			function SpinnerConfigurator(cfgProvider) {
				this.cfgProvider = cfgProvider;
				/*
					https://github.com/urish/angular-spinner
					http://spin.js.org/
				*/
				console.log(cfgProvider);
				cfgProvider.setDefaults({
					color: "white",
					scale: 1,
					width: 5,
					length: 7,
					radius: 5,
					trail: 50,
					shadow: true,
					opacity: 0.2
				});
			}
			return SpinnerConfigurator;
		}());
		SpinnerConfigurator.$inject = ["usSpinnerConfig"];
		exports.SpinnerConfigurator = SpinnerConfigurator;
	});

Angular itself is shim'd, but not angular-spinner or spin.js.  The `console.log` statement above prints out `{config: Object, themes: Object}`; that object doesn't contain a `setDefaults` method, even though I see those methods in the angular-spinner code.

Can anyone advise me on what to do?  Additional information can be provided upon request.

**Comment by Attrash-Islam** [comment]
@amyhickman Thanks for reporting. Why did you closed the issue? Is it relevant?
