### ISSUE TITLE
bower invalid meta

### ISSUE THREAD

**Issue by danielbair** [urish/angular-spinner#108]
When executing: 
bower install angular-spinner
I get:
bower angular-spinner#*   invalid-meta for:/var/folders/0f/3lm539ss48ndnzxly94g96fh0000gn/T/danielbair/bower/3b302d62deb844a749e5779b1b84b4e8-35411-uwlANk/bower.json
bower angular-spinner#*   invalid-meta The "main" field cannot contain minified files

**Comment by Attrash-Islam** [comment]
Because it has different repo https://github.com/Attrash-Islam/bower-angular-spinner
But with the same name. try to clean you bower cache please
