### ISSUE TITLE
Spinner wobbling and has a clock hand

### ISSUE THREAD

**Issue by vishaln79** [urish/angular-spinner#111]
Hello there,

I did a bower install of angular-spinner and used it according to instructions, with configuration set to {radius: 30, width: 8, length: 16}. I have used this before with no problems. For this particular app, I am getting a spinner that is wobbling and that has a clock hand that is spinning simultaneously as well. Any ideas what might be going on? (Screenshot attached)

Thanks!
Vishal.
![spinner](https://user-images.githubusercontent.com/7884587/31684290-35083c24-b34d-11e7-96d4-50b07bf04773.png)

**Comment by Attrash-Islam** [comment]
Hi @vishaln79 ,
Thanks for reporting.

This angular-spinner library is just wrapping the original one. Maybe it's related to spin.js. Can you produce this on jsbin?

**Comment by vishaln79** [comment]
It turns out that I was inadvertently using the patternfly, a bootstrap based library, css in my index.html. This was what was causing the wobbling. Apologies!

**Comment by Attrash-Islam** [comment]
I'm glad that you solved the issue @vishaln79 😄
