### ISSUE TITLE
Using spinner in angular 2+ application

### ISSUE THREAD

**Issue by sbusch99** [urish/angular-spinner#112]
I'm trying to using the spinner in an Angular 4 environment. Does this require me to install angularjs? If not, it would be great if you had an example of how to use the spinner in an Angular 2+ ONLY environment.

Thanks.

**Comment by Attrash-Islam** [comment]
Hi @sbusch99 ,
Thanks for reporting.

I really don't know anything about Angular 2+ applications. @urish Do you have any instructions?

**Comment by sbusch99** [comment]
There is a quite a bit involved in doing so - AngularJS and Angular (2+) have lots not in common. Ultimately, I rolled my own, wrapping http://spin.js.org/.

**Comment by Attrash-Islam** [comment]
Closing this issue since this wrapper is developed as an AngularJS (1.x) wrapper. Have fun wrapping spin.js :+1:
