### ISSUE TITLE
Spinner not displayed from when invoked from AngularJS HttpInterceptors

### ISSUE THREAD

**Issue by Sandeep-G** [urish/angular-spinner#114]
I'm trying to display the spinner on my AngularJS application whenever an $http call is made. For this I'm calling the stop and spin from inside a http interceptor. However the spinner doesn't get displayed certain times, at least not until the response comes back from the call. 

I tried setting up debug points in the intercecptors and noticed that the spinner doesn't get displayed after the spin function is called, but is displayed once the response from the call is received, and then disappears again quickly.

Is there a specific way to handle usage which http interceptor?

**Comment by Attrash-Islam** [comment]
Hi @Sandeep-G ,
Thanks for reporting. I'll try to produce this, and if it's working I'll add to Examples folder.

**Comment by Attrash-Islam** [comment]
Hi @Sandeep-G ,
I've done my research and found this article really useful stating the issue:
https://uithought.wordpress.com/2016/06/13/angularjs-injecting-service-into-a-http-interceptor-circular-dependency/

You should use $injector since you are trying to inject service in $compile phase

**Comment by Attrash-Islam** [comment]
I'd "really" recommend to not link your spinner with the HttpInterceptor because that would be the worst abstraction made in the history of Client-Side programming :wink: I'm just kidding with you :sweat_smile: , but that is a really bad since all background requests will trigger that spinner unless you made some kind of implementation to bypass this behavior.

**Comment by Attrash-Islam** [comment]
I'd "really" recommend not to link your spinner with the HttpInterceptor because that would be the worst abstraction in the client-side world since all background requests will trigger that spinner unless you made some kind of implementation to bypass this behavior
