### ISSUE TITLE
Noob Question : How Can I change the spinner itself.

### ISSUE THREAD

**Issue by tucibeyin** [urish/angular-spinner#115]
Hello,

I'm using angular-spinner and I would like to change the view of spinner. How can I change it. Is there a way that change it or I have to use it as it is.

**Comment by Attrash-Islam** [comment]
Hi @tucibeyin ,
The angular-spinner thing is just a wrapper for the original spin.js, so you can look at the spin.js view configuration.

![image](https://user-images.githubusercontent.com/7091543/32889073-0c90f5a0-cad2-11e7-8aa2-7859d0aa0db3.png)

I hope that helped :wink:

**Comment by tucibeyin** [comment]
Sorry if I disturb you again for second noob question. 

I'm showing us spinner in a span and inorder to customize it I used usSpinnerConfigProvider like :

![image](https://user-images.githubusercontent.com/6564339/32945016-e255a7f0-cba2-11e7-9e6c-2dddb1dd7eb9.png)

What I wonder is how can I set my gif file ( like background or content I don not know. ) in order to change the appearance of it. 

(Maybe the root question is that is there any documentation that I can read about what does usSpinnerConfigProvider do for me and usage of setTheme ? Maybe ı can find the answer in it. )

Thank you @Attrash-Islam  !

**Comment by Attrash-Islam** [comment]
The usage is found in the main page here on Github. 

Themes provide named default options for spinners. Any options passed from a directive still override these.

```js
myapp.config(['usSpinnerConfigProvider', function (usSpinnerConfigProvider) {
    usSpinnerConfigProvider.setTheme('bigBlue', {color: 'blue', radius: 20});
    usSpinnerConfigProvider.setTheme('smallRed', {color: 'red', radius: 6});
}]);
```
```html
<span us-spinner spinner-theme="smallRed"></span>
```

The important thing to note here that the theme configuration must be injected into the config phase
**myapp.config** as shown above in the example.

If you have any problems try to produce a jsbin example and I'll be glad to help
