### ISSUE TITLE
Position Relative to Parent Container

### ISSUE THREAD

**Issue by erslater** [urish/angular-spinner#42]
It would be nice if we could place it in a container and position it both vertically and horizontally relative to the parent.

**Comment by normanhh3** [comment]
It did seem like from the Plunkr demo that it really just positions itself on the center of the page no matter what kind of html nesting I did to it.

**Comment by cjones26** [comment]
I'm seeing the same behavior and agree that this seems like critical functionality.

**Comment by urish** [comment]
try giving the parent a "position: relative" css attribute. Example:

https://jsfiddle.net/o65nz3o4/6/

**Comment by erslater** [comment]
@urish I would suggest making position: relative the default as opposed to an override.  Most of the time these days we are updating a specific portion of a page and not the whole thing.  The spinner should be applicable to that portion.

**Comment by axelson** [comment]
+1 for making `position: relative` the default. I'd love the spinner to be centered over the element rather than globally on the page. Or at least make this obvious from the Readme. If angular-spinner doesn't handle this use-case well I may have to look for a different approach.
