### ISSUE TITLE
Is it possible to set a background behind the spinner?

### ISSUE THREAD

**Issue by Bandes** [urish/angular-spinner#49]
I'd love to have a white spinner in a black box like in the demo on spin.js' homepage - is that something that can be done with this directive?

**Comment by floydpink** [comment]
+1

**Comment by kishankanugula** [comment]
http://plnkr.co/edit/0GnAqUE8jcmXb2J1BgRq?p=preview

**Comment by mohammad6006** [comment]
full page background : http://plnkr.co/edit/dEInZl3EJs6BO5jLtE9k?p=preview

Thanks @kishankanugula

**Comment by bennyp123** [comment]
Fill the element
```
.spinner {
  width: 100%;
  height: 100%;
}
.spinner:before {
  background-color: $gray-lighter;
  top: -50%;
  left: -50%;
  border-radius: 5px;
  width: 100%;
  height: 100%;
  position: relative;
  display: block;
  content: " ";
}
```

**Comment by jlmonroy13** [comment]
you have to put this class to your span spinner: 

.spinner__container {
    background-color: rgba($brand-default, 0.7);
    border-radius: 10px;
    height: 70px;
    left: 50%;
    position: absolute;
    top: 50%;
    transform: translate(-50%,-50%);
    width: 70px;
    z-index: 3;
}

**Comment by Attrash-Islam** [comment]
Hi all,
Thanks for your support.

Everyone suggested great workarounds and they're all accepted.
If you look at spin.js own implementation they're styling a parent div for the spinner tag :smile: 

I'll close this issue
