### ISSUE TITLE
How can I specify the target of the spinner?

### ISSUE THREAD

**Issue by calloncampbell** [urish/angular-spinner#54]
"The spin() method creates the necessary HTML elements and starts the animation. If a target element is passed as argument, the spinner is added as first child and horizontally and vertically centered."

I don't really see how I can do this with the angular-spinner. If it's possible, can you show me how?

Here is an example using the raw javascript version: http://jsfiddle.net/fgnass/q6ou3dt7/

Thanks

**Comment by urish** [comment]
You just attach the "us-spinner" attribute to the element, like the example in the readable:

`<span us-spinner="{radius:30, width:8, length: 16}"></span>`

**Comment by calloncampbell** [comment]
regardless of which element you attach the "us-spinner" attribute to, the spinner never renders next to the element.
<img width="580" alt="sshot-1" src="https://cloud.githubusercontent.com/assets/4095080/9338348/451140e4-45b2-11e5-9c7b-f0c9b77caba4.png">

**Comment by urish** [comment]
Please try applying the following styles to the target element:

`display:inline-block; position: relative;`
