### ISSUE TITLE
SpinnerConstructor is not a function error

### ISSUE THREAD

**Issue by markolalic** [urish/angular-spinner#58]
Hi I have a problem running a spinner. I'm getting this error:

SpinnerConstructor is not a function

in my console logs. I installed this extension via bower. Injected both spin.js and angular-spinner.js., included 'angularSpinner' module into my js page, created simple function that calls spinner to open and it is not showing. Did anyone got this error?

Thanks in advance
Marko

**Comment by jcieslar** [comment]
Yes, I have the same issue.

**Comment by wytrych** [comment]
Same for me

**Comment by akiokio** [comment]
same here but only when the code is minified

**Comment by bartes** [comment]
This was a fix for browserify:

window.Spinner = require('spin.js')
require('angular-spinner')

**Comment by SashaKolda** [comment]
The problem persists for me to. Installed via bower.

**Comment by akiokio** [comment]
Fixed, actually i had some junk files in my dist folder named spinjs (not spin.js) after I cleaned the error went away
