### ISSUE TITLE
How do I easily plugin other spinners as to this ?

### ISSUE THREAD

**Issue by ishandutta2007** [urish/angular-spinner#59]

**Comment by urish** [comment]
Can you give an example?

**Comment by Attrash-Islam** [comment]
Hi @ishandutta2007 ,
If you mean that this angular-wrapper is capable of Open-Closed principle which gives you to implement some sort of class and write your own implementation as a plug-able system (Like: infinite-autocomplete), then the answer is No.

This angular wrapper is depending only on `spin.js` library directly
