### ISSUE TITLE
support for spinner-on attr

### ISSUE THREAD

**Issue by marknadig** [urish/angular-spinner#65]
Would you support a PR for supporting a 'spinner-on' attr that would essentially start a watch and start/stop the spinner based on the value of that attr?

<span us-spinner spin-on='ctrl.isSaving'></span>

**Comment by moravcik** [comment]
+1
this would help me too

**Comment by urish** [comment]
Yea, a PR for that would be appreciated. I think that adding a new attribute for the existing directive would be a better approach than suggested in #47...

Thanks!
