### ISSUE TITLE
Ploblem about angularjs-spinner

### ISSUE THREAD

**Issue by avatarr** [urish/angular-spinner#72]
when I access any page that include "us-spinner" directive I go error like this "TypeError: b is not a function" 
error on console
![screen shot 2558-10-27 at 14 02 29](https://cloud.githubusercontent.com/assets/1640817/10751751/a834b900-7cb5-11e5-8062-5f5e644f99d5.png)

my Dependencies 

![screen shot 2558-10-27 at 14 18 28](https://cloud.githubusercontent.com/assets/1640817/10751759/c40a958c-7cb5-11e5-84a1-9bde1825eded.png)

I think it conflict with some Dependency, but I'm not sure

**Comment by boddicheg** [comment]
@avatarr, please replace minified file "/bower_components/angular-spinner/angular-spinner.min.js" to non-minified "/angular-spinner/angular-spinner.js" and check error. Thanks

**Comment by justcald** [comment]
I am having the same issue, and then when I change from the minified version the error changes to 

TypeError: SpinJSSpinner is not a function

Not sure if there is something we are both doing wrong?

**Comment by pasqLisena** [comment]
I have the same error!
Without minification is <code>SpinJSSpinner is not a function</code>.

**Comment by pasqLisena** [comment]
I solved! I had the import of <code>spin.js</code> after <code>angular-spinner.js</code>. I just switched the two and now it works :smile:

**Comment by deepakmani** [comment]
Thanks for leaving this comment. Its working for me now.

**Comment by nkantkumar** [comment]
First spin.js and then angular-spinner.js should be loaded. Please avoid to use minified version. It will work.

**Comment by Attrash-Islam** [comment]
Hi community folks,

We've decided to refactor the whole base code because of the many requests of webpack and amd compatibility issues, and we're using already webpack in master branch (+TypeScript).

You don't need to include spin.js anymore for angular-spinner to work, because it resolves as a dependency and webpack is bundling the both into one base code
