### ISSUE TITLE
Grouping of spinners

### ISSUE THREAD

**Issue by MangeshPimpalkar** [urish/angular-spinner#73]
Hi
Is there a way of grouping of spinners.

```
 '<span us-spinner spinner-key="spinner-1"></span>
  <span us-spinner spinner-key="spinner-2"></span>'
```

...dynamic

if want to have a group so that i can stop all the spinners by group and then activate only one.

**Comment by urish** [comment]
See #67 , please comment there if you think that feature can help you achieve what you need... Thanks!

**Comment by MangeshPimpalkar** [comment]
+1
