### ISSUE TITLE
multiple spinners with different options?

### ISSUE THREAD

**Issue by sonicparke** [urish/angular-spinner#76]
It seems that once a spinner is started the config options that are passed into that spinner override any other config options that are passed into any additional spinners on the page. Is this a bug or intended behavior or am I just doing something wrong?

Here's a plunker to illustrate: http://plnkr.co/edit/XLK0emyBzDij0pYv6EqO?p=preview

**Comment by BenMGilman** [comment]
+1

**Comment by igler** [comment]
+1

**Comment by igler** [comment]
Changing line 85 in https://github.com/urish/angular-spinner/blob/master/angular-spinner.js to

<code>options = angular.extend({}, usSpinnerConfig.config, usSpinnerConfig.themes[attr.spinnerTheme]);
</code>

helped in my scenario where colors got mixed up.

**Comment by lucaferri** [comment]
+1

I think the problem could be line [90](https://github.com/urish/angular-spinner/blob/master/angular-spinner.js#L90)
```javascript
scope.spinner = new SpinJSSpinner(options);
```
because every new instance of SpinJs override the previous one.

**Comment by dorr-fg** [comment]
+1

**Comment by rich186** [comment]
+1
