### ISSUE TITLE
Check if spinner is active

### ISSUE THREAD

**Issue by jamespsterling** [urish/angular-spinner#79]
Is there a way to check if the spinner is active via the spinner service?

**Comment by Attrash-Islam** [comment]
Hi @jamespsterling ,
Thanks for reporting.

Based on the service code, we don't save the state of spinner key active status. That is possible by saving to hash object when spin()/stop() get executed:

interface HashedObject {
    [spinnerKey:string]: boolean
}

Alternatively, you can check if the directive element have children (children.length >= 1), if true then the spinner is active else (children.length === 0) the spinner is not active

Simple example:

```html
<div id="test">
    <div ui-spinner spinner-key="spinner-1"></div>
</div>
```

```js
//Will check if spinner-1 key is active or not under test ID selector
console.dir(document.getElementById('test')
        .querySelector('[spinner-key=spinner-1]').children.length)
```

If the case requested to implement the hashObject I'd be glad to commit a change to the service so we have a method called `isSpinnerActive(spinnerKey:string):boolean`

Let me know :wink:
