### ISSUE TITLE
Working with cordova?

### ISSUE THREAD

**Issue by jycouet** [urish/angular-spinner#82]
This code works perfectly:

``` javascript
app.controller('MyController', ['$scope', 'usSpinnerService', function($scope, usSpinnerService){
    $scope.startSpin = function(){
        usSpinnerService.spin('spinner-1');
    }
    $scope.stopSpin = function(){
        usSpinnerService.stop('spinner-1');
    }
}]);
```

But this one:

``` javascript
app.controller('MyController', ['$scope', 'usSpinnerService', function($scope, usSpinnerService){
    $scope.myClick = function(){
        usSpinnerService.spin('spinner-1');
        cordova.exec(function(){
            $scope.data = "Done";
            usSpinnerService.stop('spinner-1');
        }, function(err) {
            callback('Nothing to echo.');
        }, "Echo", "echo", []);
    }
}]);
```

the spin start but never stop!
If I remove usSpinnerService.spin('spinner-1'); and usSpinnerService.stop('spinner-1');
Then I can see my $scope.data set to "Done"

Can you help me please?

Thank you

**Comment by Attrash-Islam** [comment]
Hi @jycouet and thanks for opening this issue.

Why you're using cordova.exec? Cordova is wrapping what you see in browser into the mobile, so what works in browsers should work in mobile (except what related to cordova-webview and compatibility issues).

What you're trying to do?

**Comment by jycouet** [comment]
Hi, 
Sorry, I had this a long time ago.
My call to cordova was not placed well.

We can close this question.

Thank you

**Comment by Attrash-Islam** [comment]
Thanks for your response
