### ISSUE TITLE
Don't Show Spinner Immediately - Delay for 1/2 Second

### ISSUE THREAD

**Issue by eriksendc** [urish/angular-spinner#83]
Hi All,

Typically we want spinners to indicate a long-running (>1/2 sec, maybe >1s) process. I was wondering if there was an appropriate "angular way" to use angular-spinner to delay the showing of the spinner. I'm thinking of some kind of option whereby once the spinner-on condition became true there would be a wait of X ms before really showing the spinner. If the spinner-on condition wasn't still true after that delay, then simply don't ever show the spinner.

I'm trying to avoid split-second "flashing" of the spinner. Any ideas?

Thanks in advance.

Regards,
Brian Eriksen

**Comment by eriksendc** [comment]
I think I've got some changes to angular-spinner.js that I'd like to contribute that accomplish what I mentioned above. Here's what I've done:

I'm using `$timeout`, so I added it to the `.directive()` call:
```
.directive('usSpinner', ['SpinJSSpinner', 'usSpinnerConfig', '$timeout', 
           function (SpinJSSpinner, usSpinnerConfig, $timeout) {...
```
I'm using a new attribute `spinnerDelay` (`spinner-delay="####"`) to designate the millisecond delay for starting the spinner. I parse and store the value in `scope.spinnerDelay`. I put this code just above `if (attr.spinnerOn) {...`:
```
scope.spinnerDelay = 0;

if (angular.isDefined(attr.spinnerDelay) && 
    attr.spinnerDelay !== null && 
    attr.spinnerDelay.trim().length > 0 && 
    !isNaN(attr.spinnerDelay) && 
    attr.spinnerDelay.indexOf('.') < 0) {
    var spinnerDelay = parseInt(attr.spinnerDelay);
    if (spinnerDelay > 0) {
        scope.spinnerDelay = spinnerDelay;
    }
}
```
inside `if (attr.spinnerOn) {...` I modified the implementation of the `if (spin)` case (inside the function called by `$watch`). It used to just call `scope.spin()`, opposite the `scope.stop()` in the else. I preserve that behavior if the delay is 0 (either due to the attribute not existing, or existing with an invalid value), but if the delay is > 0 then I delay using $timeout, test the `spinnerOn` attribute again, and then call `scope.spin()` if the evaluation of `spinnerOn` is still `true`:
```
if (attr.spinnerOn) {
    scope.$watch(attr.spinnerOn, function (spin) {
        if (spin) {
            if (scope.spinnerDelay === 0) {
                scope.spin(); //old behavior
            } else {
                $timeout(function () {
                    var shouldStillStart = scope.$eval(attr.spinnerOn);
                    if (shouldStillStart) {
                        scope.spin();
                    }
                }, scope.spinnerDelay);
            }
        } else {
            scope.stop();
        }
    });
}
```
Now I can use the following in my views:
```
<span us-spinner spinner-on="searching && !initializing" spinner-delay="500"></span>
```
I've modified my local angular-spinner.js and tested this quite a bit. Unfortunately I'm not too familiar with git or github other than poking around to find issues to my problems. I'll try to find some time this weekend to learn enough to follow the contribution steps / instructions, but forgive me in advance as I'm a newbie with contributing.

Thanks,
Brian Eriksen

**Comment by Attrash-Islam** [comment]
Hi @eriksendc ,
Thanks for reporting

Why don't you wrap the 'us-spinner:spin' event with $timeout instead of extending the library core with new feature?

**Comment by eriksendc** [comment]
@Attrash-Islam Oh you know that might be a way to implement the behavior we were after... If you want to give it a go, feel free!

**Comment by Attrash-Islam** [comment]
You can create a timedService which calls the original service (usSpinner service) with $timeout. Do you want an example for this?

**Comment by Attrash-Islam** [comment]
```js
class TimesSpinnerService {
 constructor(private $timeout:ng.ITimeoutService, private UsSpinnerService:IUsSpinnerService){}
 static $inject = ['$timeout', 'UsSpinnerService'];

spin(key:string){
 this.$timeout(() => {
  this.UsSpinnerService:IUsSpinnerService.spin(key);
}, 500);
}

stop(key:string) {
 this.UsSpinnerService:IUsSpinnerService.stop(key);
}

}
```

**Comment by Attrash-Islam** [comment]
And use always this TimedSpinnerService instead of us-spinner service

**Comment by Attrash-Islam** [comment]
I'll close this, if you think that this is not resolving the issue feel free to reopen it

**Comment by eriksendc** [comment]
@Attrash-Islam Thanks for sharing this idea. I guess my point was that I came up with something that could be added to the codebase and then be a feature for everyone. What you're suggesting is for me to write code in my project that would be the stuff I'd think belongs in angular-spinner directly. Maybe I'm not being clear, or maybe I'm not getting your solution. Let me know if I'm making sense here. I think having the delay be triggerd by including an optional attribute right in the html of a page really makes it easy for the user of angular-spinner, no?

Regards,
-Brian Eriksen

**Comment by Attrash-Islam** [comment]
Thanks @eriksendc for making this discussion useful for others.

Mainly, I believe that libraries should contain the most important and straight forward regards the problems they attempt to resolve, and I fully understand your words regards pushing this into the library core and not as an extension like the example attached above.

Give me the chance to review this issue again

What you think @urish ?

**Comment by pm3053mg13** [comment]
I have a code in which the spinner is not spinning without $timeout. In all other files the spinner is working perfectly fine without $timeout but in one file it is not.

What could be the possible problem with that.

1) javascript code: (this code is not working without $timeout)

(function () {
    var controllerId = "MyController";
    angular.module(MyConfiguration.moduleName).controller(controllerId, ['$scope', '$rootScope', '$window', '$state', 'MyService', 'usSpinnerService', 'Common','$timeout',
    function ($scope, $rootScope, $window, $state, MyService, usSpinnerService, common,$timeout) {

        $scope.identity = $rootScope.identity;
     
        $scope.model = {};

        $scope.listingId = 0;
         
        function get() {
                usSpinnerService.spin('showspinner');
            
           MyService.get(userId).then(function (data) {
               
                $scope.model = data;
                $scope.listingId = data.CurrentListing.Id;
                $rootScope.$broadcast('getMyDetails', { listingId: $scope.listingId });
               usSpinnerService.stop("showspinner");
            }, function () {
              usSpinnerService.stop('showspinner');
            });
        }           
        common.activateController([getLeases()], controllerId);
    }]);
}());

2) html code: 

 <div class="col-md-8" us-spinner spinner-key="showspinner">
    
</div>

*Kindly help in solving this problem.

Thanks
Piyush Munjal

**Comment by Attrash-Islam** [comment]
Hi @pm3053mg13 ,
Where you're using the $timeout?

Mainly, In AngularJS 1.x, a code that is working just in $timeout execution means that some non-angularjs code is triggering that code and Angularjs don't know about it, such as: mutating the angularjs model in JQuery scope (As been the most famous case).

Can you create a fiddle for this? because I don't see you use $timeout up there, you're just injecting it

**Comment by pm3053mg13** [comment]
Hi @Attrash-Islam 

I am using the $timeout like this and it is working fine but without it the spinner is not working.

Thats why i have posted the code without $timeout so that if there is any problem someone could detect and tell.
$timeout(function(){  
   usSpinnerService.spin('showspinner');
});

**Comment by Attrash-Islam** [comment]
How you call get() method?

**Comment by pm3053mg13** [comment]
I am calling get method using  common.activateController([getDashboard()], controllerId);

**Comment by Attrash-Islam** [comment]
Can you put the activateController implementation?

**Comment by eriksendc** [comment]
@Attrash-Islam Just a reminder, my original code posted (2nd comment) helps by abstracting away the need to code for the timeout. With the code change I suggest then all the user of the directive need do is pass in a configured value. Anyways, have you considered this as an addition?

**Comment by Attrash-Islam** [comment]
Hi Eric,
Yes. I'd be pleased if you send a pull request, and I'll merge it.

Regards pm3053mg13 problem, I guess it's related to modifying the scope model in a non-angular methods, so the digest is not knowing about the change, If he doesn't pass your new attribute.

Note: please replace this code:
```js
if (angular.isDefined(attr.spinnerDelay) && 
    attr.spinnerDelay !== null && 
    attr.spinnerDelay.trim().length > 0 && 
    !isNaN(attr.spinnerDelay) && 
    attr.spinnerDelay.indexOf('.') < 0) {
    var spinnerDelay = parseInt(attr.spinnerDelay);
    if (spinnerDelay > 0) {
        scope.spinnerDelay = spinnerDelay;
    }
}
```

With one line regex 😉
