### ISSUE TITLE
travis error

### ISSUE THREAD

**Issue by Minglee01** [urish/angular-spinner#86]
Im using 0.8.0
and just today as 0.8.1s released im getting an error in travis
![screen shot 2016-02-17 at 14 37 27](https://cloud.githubusercontent.com/assets/10808373/13112742/135baa1e-d584-11e5-9d97-d9a1b4e31714.png)

**Comment by urish** [comment]
0.8.0 is still available: https://github.com/urish/angular-spinner/tree/0.8.0

When I run locally `bower install angular-spinner#0.8.0` it installs successfully. Can you try this and see if it works for you?

**Comment by Minglee01** [comment]
it does but my travis tests kept failing i had to install 0.8.1.
Thanks.
I dont think this is an issue anymore though so im closing this issue.
