### ISSUE TITLE
Redundant button in Plunker Demo

### ISSUE THREAD

**Issue by chaitanyathengdi** [urish/angular-spinner#90]
Not really an issue, but in the demo, there's an extra button sitting idle when the spinner is active/inactive. It can be hidden with ng-if:

http://plnkr.co/edit/l41krgmax1GdXRd6aD2q?p=preview

**Comment by Attrash-Islam** [comment]
Hi @chaitanyathengdi ,
Thanks for your grateful contribution.

I pushed a commit and linked it with the issue with your contribution credits :1st_place_medal:
