### ISSUE TITLE
message: extraneus

### ISSUE THREAD

**Issue by HectorRPL** [urish/angular-spinner#94]
Hey comunity whats up!
I use `meteor` and `angular-meteor`
I execute `$ npm install angular-spinner`
the next message appear:
```
+-- angular@1.5.8
+-- angular-animate@1.5.8
+-- angular-messages@1.5.8
+-- angular-meteor@1.3.11
+-- angular-spinner@0.8.1  extraneous
+-- angular-ui-bootstrap@1.3.3
+-- angular-ui-router@0.2.18
+-- angular-utils-pagination@0.11.1
+-- bootstrap@3.3.7
+-- bootstrap-social@5.0.0
`-- font-awesome@4.7.0
```
As you see  in the line `+-- angular-spinner@0.8.1  extraneous`  **extraneous** is strange.
some ideas to solve this?
Thanks for read!

**Comment by urish** [comment]
Hi, the happens because `angular-spinner` is not present in your package.json. You can solve it by running:

    npm install --save angular-spinner
