### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by urish** [urish/angular-spinner#95]
This project needs some love, and I can no longer find the time required to maintain it. If anybody wants to stand up as a new maintainer, please comment here. Thanks!

**Comment by Attrash-Islam** [comment]
Hi Uri,
I'd like to request to maintain this :)

This is how I write code (Fresh pull request):
https://github.com/ryanmcdermott/typescript-makefile/pull/1 (see run.js file and compare it with Makefile)

If you see that this is relevant I'd be glad to receive your response.

Thanks

**Comment by urish** [comment]
Thank you Islam! 

Maintaining the project mainly consists of looking at pull requests from other users, issues, giving them feedback and making sure that everything fits together.

Of course you can implement new features yourself, but I just want to make sure that you are also aware of the community aspects of the project too. Does this sound like something that works for you?

**Comment by Attrash-Islam** [comment]
Hi Uri,
Mainly if you'd like to start with something, is to implement webpack for umd (as I noticed that most of the bugs and pull requests were about breaking things regards modules approaches), and to divide the code into seperated file and lastly migrate to TypeScript and that wouldn't take that much of time.

What's your opinion?

**Comment by urish** [comment]
I like that direction. As for webpack/umd - I think that one of the major problems is the dependency on `spin.js`. Just a point to keep in mind. I'd love to see the project evolving into a well-organized, typescript code base. It will be lovely if you manage to do that.

I added you as a contributor on github. Once you have a new release ready, ping me and I will also add you as a maintainer to the npm package. Also, feel free to add your credits in the README.

**Comment by shairez** [comment]
good job @Attrash-Islam ! 

Good luck!

**Comment by Attrash-Islam** [comment]
I can start by closing this :D
